from re import match


print("ingrese dos numeros enteros:")
num1 = int(input("Numero 1: "))
num2 = int(input("Numero 2: "))

print("1. calculadora")
print("***************************************************")
print("* CALCULADORA AVANZADA *")
print("***************************************************")
print()
print("--- Operaciones Aritmeticas Basicas ---")
print(" 1. Sumar")
print(" 2. Restar")
print(" 3. Multiplicar")
print(" 4. Dividir")
print()
print("--- Analisis y Propiedades de Numeros (Resultado de la suma de ambos numeros) ---")
print(" 5. Comparar (mayor, menor o igual)")
print(" 6. Positividad si el resultado es positivo o negativo")
print(" 7. Paridad (par o impar)")
print(" 8. Tipo de numero (entero o decimal)")
print(" 9. Primalidad (primo o compuesto)")
print("10. Perfeccion (perfecto o no)")
print("11. Amistad (amigos o no)")
print("12. capicua o no")
print()
print("--- Analisis de Secuencias y Series ---")
print("13. Pertenencia a la secuencia Fibonacci")
print("14. Verificar si es un numero triangular")
print("15. Verificar si es un numero cuadrado perfecto")
print("---------------------------------------------------")

print("Ingrese el numero de la operacion que desea realizar:")
opcion = int(input())

match opcion:
    case 1: print(num1 + num2)
    case 2: print(num1 - num2)
    case 3: print(num1 * num2)
    case 4: print(num1 / num2 if num2 != 0 else "Error: Division por cero")
    case 5: print("Mayor" if num1 > num2 else "Menor" if num1 < num2 else "Igual")
    case 6: print("Positivo" if (num1 + num2) > 0 else "Negativo")
    case 7: print("Par" if (num1 + num2) % 2 == 0 else "Impar")
    case 8: print("Entero" if (num1 + num2) % 1 == 0 else "Decimal")
    case 9: print("Primo" if all((num1 + num2) % i != 0
                      for i in range(2, int((num1 + num2) ** 0.5) + 1))
                        and (num1 + num2) > 1 else "Compuesto")
    case 10: print("Perfecto" if (num1 + num2) == sum(i for i in range(1, (num1 + num2) // 2 + 1) if (num1 + num2) % i == 0) else "No Perfecto")
    case 11: print("Amigos" if (num1 + num2) == (sum(i for i in range(1, num1) if num1 % i == 0) +
                        sum(i for i in range(1, num2) if num2 % i == 0)) else "No Amigos")
    case 12: print("Capicua" if str(num1 + num2) == str(num1 + num2)[::-1] else "No Capicua")
    case 13: print("Pertenece a Fibonacci" if (num1 + num2)
    in {0, 1} or any((5 * (x ** 2) + 4) in {0, 1} for x in [num1 + num2, -(num1 + num2)]) else "No pertenece a Fibonacci")
    case 14: print("Triangular" if (((8 * (num1 + num2)+1) ** 0.5).is_integer()) else "No Triangular")
    case 15: print("Cuadrado Perfecto" if (int((num1 + num2) ** 0.5) ** 2 == (num1 + num2)) else "No Cuadrado Perfecto")
    case _:
        print("Opcion no valida")
